version: '3.9'
services:
  web:
    container_name: django
    build:
      context: django
    env_file:
      - ./django/conf.env
      - ./sql/conf.env
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      mqtt:
        condition: service_started
  db:
    image: mysql
    restart: always
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10
    volumes:
      - ./sql/data/:/var/lib/mysql
    env_file:
      - ./sql/conf.env
    ports:
      - 3306:3306
  mqtt:
    image: eclipse-mosquitto:2
    restart: always
    volumes:
      - type: bind 
        source: ./mqtt/config/
        target: /mosquitto/config/
      - type: bind
        source: ./mqtt/log/
        target: /mosquitto/log/
    ports:
      - 1883:1883
      - 9001:9001
