# Generated by Django 4.1.7 on 2024-03-12 16:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeRefernece',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('node_name', models.CharField(max_length=255, unique=True)),
                ('major_version', models.PositiveIntegerField()),
                ('minor_version', models.PositiveIntegerField()),
                ('patch_version', models.PositiveIntegerField()),
                ('ref_number', models.IntegerField(default=1)),
                ('ref_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
