# Generated by Django 4.1.7 on 2024-07-25 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeRefernece',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('node_name', models.CharField(max_length=255, unique=True)),
                ('ref_number', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
