"""
Django settings for domena project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os

from pathlib import Path
from datetime import timedelta
from rest_framework.settings import api_settings

from .plugins import PLUGINS
from devices.plugin_loader import scan_for_plugin

import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType

import saml2

from django.urls import reverse_lazy

# a server version
SERVER_VERSION="0.5"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


ROOT_API_PATH=os.getenv("FETCH_API_ROOT_PATH")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["zerotwo.tenere.konar.pwr.edu.pl","staging.zerotwo.tenere.konar.pwr.edu.pl"]
CORS_ALLOWED_ORIGINS = ["https://zerotwo.tenere.konar.pwr.edu.pl", "https://staging.zerotwo.tenere.konar.pwr.edu.pl"]
CSRF_TRUSTED_ORIGINS=["https://zerotwo.tenere.konar.pwr.edu.pl", "https://staging.zerotwo.tenere.konar.pwr.edu.pl"]

if os.environ.get("DJANGO_MODE")=='DEBUG':
    ALLOWED_HOSTS.extend([os.environ.get('IP_ADDR'),"localhost"])
    CORS_ALLOWED_ORIGINS.extend(["http://"+os.environ.get('IP_ADDR') ,"http://localhost"])
    CSRF_TRUSTED_ORIGINS.extend(["http://"+os.environ.get('IP_ADDR'),"http://localhost"])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'auth02',
    'devices',
    'nodeacl',
    'nodes',
    'importer',
    'rest_framework',
    'knox'
] + scan_for_plugin()+['mqtt']

MQTT_SERVER="mqtt"
MQTT_USER=os.environ.get('MQTT_USER')
MQTT_PASSWORD=os.environ.get('MQTT_PASSWORD')
MQTT_PORT=int(os.environ.get('MQTT_PORT'))
MQTT_KEEPALIVE =int(os.environ.get('MQTT_KEEPALIVE'))

AUTH_USER_MODEL = 'auth02.O2User' 


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'domena.middleware.SessionChecker'
    ]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

AUTHENTICATION_BACKENDS=["django.contrib.auth.backends.ModelBackend"]

if os.getenv("USE_SAML"):
    INSTALLED_APPS.append('djangosaml2')
    MIDDLEWARE.append('djangosaml2.middleware.SamlSessionMiddleware')
    AUTHENTICATION_BACKENDS.append('djangosaml2.backends.Saml2Backend')

    SAML_SESSION_COOKIE_NAME = os.getenv("SAML_COOKIE_NAME")
    SAML_SESSION_COOKIE_SAMSITE = os.getenv("SAML_COOKIE_SAMSITE")

    LOGIN_URL = os.getenv("SAML_LOGIN_URL")
    SESSION_EXPIRE_AT_BROWSER_CLOSE = True

    SAML_DEFAULT_BINDING = saml2.BINDING_HTTP_POST
    SAML_LOGOUT_REQUEST_PREFERRED_BINDING = saml2.BINDING_HTTP_POST

    SAML_IGNORE_LOGOUT_ERRORS = True
    SAML_DJANGO_USER_MAIN_ATTRIBUTE = os.getenv("SAML_DJANGO_USER_MAIN_ATTR")
    ACS_DEFAULT_REDIRECT_URL = reverse_lazy(os.getenv("SAML_REDIRECT_URL"))

    SAML_ATTRIBUTE_MAPPING = {
        'uid': (os.getenv("SAML_ATTR_MAP_USERNAME")),
        'mail': (os.getenv("SAML_ATTR_MAP_MAIL")),
        'cn': (os.getenv("SAML_ATTR_MAP_CN")),
        'sn': (os.getenv("SAML_ATTR_MAP_SN")),
    }

    import saml_config
    



if os.getenv("USE_LDAP"):
    AUTHENTICATION_BACKENDS.append["django_auth_ldap.backend.LDAPBackend"]
    if os.getenv("LDAP_SERVER_ADDR") is not None:
        AUTH_LDAP_SERVER_URI = os.getenv("LDAP_SERVER_ADDR")
        
    AUTH_LDAP_BIND_DN = ""
    AUTH_LDAP_BIND_PASSWORD = ""
    AUTH_LDAP_USER_SEARCH = LDAPSearch(
    os.getenv("LDAP_BASE_DN"), ldap.SCOPE_SUBTREE, os.getenv("LDAP_FILTERSTR")
    )

    AUTH_LDAP_CACHE_TIMEOUT = 3600

    AUTH_LDAP_USER_ATTR_MAP = {
    "username":os.getenv("LDAP_MAP_USERNAME"),
    "first_name": os.getenv("LDAP_MAP_FIRSTNAME"),
    "last_name": os.getenv("LDAP_MAP_LASTNAME"),
    "email": os.getenv("LDAP_MAP_EMAIL")
    }

ROOT_URLCONF = 'domena.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'domena.context_pre.menu_items'
            ],
        },
    },
]

WSGI_APPLICATION = 'domena.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':os.environ.get('POSTGRES_DB'),
        'USER':os.environ.get('POSTGRES_USER'),
        'PASSWORD':os.environ.get('POSTGRES_PASSWORD'),
        'HOST':'db',
        'PORT':os.environ.get('POSTGRES_PORT')
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get('TIME_ZONE')

USE_I18N = True

USE_TZ = True

DEFAULT_SESSION_TIME=360


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('knox.auth.TokenAuthentication',)
}

REST_KNOX = {
  'SECURE_HASH_ALGORITHM': 'cryptography.hazmat.primitives.hashes.SHA512',
  'AUTH_TOKEN_CHARACTER_LENGTH': 64,
  'TOKEN_TTL': timedelta(hours=10),
  'USER_SERIALIZER': 'knox.serializers.UserSerializer',
  'TOKEN_LIMIT_PER_USER': None,
  'AUTO_REFRESH': False,
  'EXPIRY_DATETIME_FORMAT': api_settings.DATETIME_FORMAT,
}



# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STATIC_ROOT = str("/web/static")
# https://docs.djangoproject.com/en/dev/ref/settings/#static-url
STATIC_URL = "/static/"
# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#std:setting-STATICFILES_DIRS
STATICFILES_DIRS = ["/app/static/"]
# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#staticfiles-finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# MEDIA
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#media-root
MEDIA_ROOT = str("/web/media")
# https://docs.djangoproject.com/en/dev/ref/settings/#media-url
MEDIA_URL = "/media/"
