# Generated by Django 4.1.7 on 2024-02-29 10:30

import django.core.validators
from django.db import migrations, models
import re
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^/+[\\w /]+(?<!/)$'), 'String is not a valid path, must be path /.../ ')])),
                ('node', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicBeamer',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^/+[\\w /]+(?<!/)$'), 'String is not a valid path, must be path /.../ ')])),
                ('node', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicCatcher',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^/+[\\w /]+(?<!/)$'), 'String is not a valid path, must be path /.../ ')])),
                ('node', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
